export const SUPPORTED_PORTS = [
    // China
    "Shanghai, CN",
    "Ningbo, CN",
    "Shenzhen, CN",
    "Guangzhou, CN",
    "Qingdao, CN",
    "Tianjin, CN",
    "Xiamen, CN",
    "Dalian, CN",
    "Hong Kong, HK",
    "Beijing, CN",

    // Asia (Other)
    "Singapore, SG",
    "Tokyo, JP",
    "Yokohama, JP",
    "Kobe, JP",
    "Osaka, JP",
    "Busan, KR",
    "Incheon, KR",
    "Kaohsiung, TW",
    "Keelung, TW",
    "Port Klang, MY",
    "Ho Chi Minh, VN",
    "Hai Phong, VN",
    "Laem Chabang, TH",
    "Bangkok, TH",
    "Nhava Sheva, IN",
    "Mumbai, IN",
    "Chennai, IN",
    "Colombo, LK",
    "Dubai, AE",
    "Jebel Ali, AE",

    // Europe
    "Rotterdam, NL",
    "Antwerp, BE",
    "Hamburg, DE",
    "Bremerhaven, DE",
    "Felixstowe, GB",
    "Southampton, GB",
    "London, GB",
    "Liverpool, GB",
    "Le Havre, FR",
    "Marseille, FR",
    "Valencia, ES",
    "Barcelona, ES",
    "Genoa, IT",
    "La Spezia, IT",
    "Trieste, IT",
    "Piraeus, GR",
    "Gdansk, PL",
    "Gothenburg, SE",

    // North America
    "Los Angeles, US",
    "Long Beach, US",
    "New York, US",
    "Newark, US",
    "Savannah, US",
    "Houston, US",
    "Norfolk, US",
    "Seattle, US",
    "Tacoma, US",
    "Oakland, US",
    "Charleston, US",
    "Miami, US",
    "Jacksonville, US",
    "Vancouver, CA",
    "Montreal, CA",
    "Toronto, CA",
    "Halifax, CA",

    // South America
    "Santos, BR",
    "Buenos Aires, AR",
    "Callao, PE",
    "San Antonio, CL",
    "Cartagena, CO",
    "Manzanillo, MX",
    "Veracruz, MX",
    "Balboa, PA",
    "Colon, PA",

    // Oceania
    "Sydney, AU",
    "Melbourne, AU",
    "Brisbane, AU",
    "Fremantle, AU",
    "Auckland, NZ",
    "Tauranga, NZ"
].sort();
