# MarketLive Execution Index

🚀 **Status**: ACTIVE
📅 **Current Sprint**: Phase 1 (UI + Launch)

## 📂 Directories
- [**UI Specs & Checklists**](./ui/)
- [**Content Assets**](./content/)
- [**Outreach Materials**](./outreach/)
- [**Community**](./community/)
- [**Reports**](./reports/)

## ⚡ Core Documents
- [**Master Tracker**](./master_tracker.md) (Status of all tasks)
- [**UI Checklist**](./ui/ui_checklist.md) (Mandatory Design Rules)
- [**Sidebar Spec**](./ui/sidebar_spec.md) (Emoji Navigation)
- [**Landing Page Wireframe**](./ui/landing_page_wireframe.md) (Next.js Plan)

## 📢 Content Ready to Ship
- [**Blog: GeoRisk Intro**](./content/blogs/georisk_intro.md)
- [**LinkedIn Pack: Week 1**](./content/social/linkedin_week1.md)
- [**Press Release: Beta Launch**](./outreach/press_release_beta.md)

---
*Generated by MarketLive Autonomous Execution Agent*
